<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Course extends \App\Entity\Course implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseNumtransaction', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseNbpassagers', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseHeuredepart', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseHeurearrivee', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseStatut', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'coursePrix', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseDistance', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'vehiculeNumplaques', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idAdressearrivee', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idStatutcourse', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idFacture', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idAdressedepart', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idClient', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idEmploye', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseClient'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseNumtransaction', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseNbpassagers', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseHeuredepart', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseHeurearrivee', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseStatut', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'coursePrix', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseDistance', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'vehiculeNumplaques', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idAdressearrivee', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idStatutcourse', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idFacture', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idAdressedepart', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idClient', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'idEmploye', '' . "\0" . 'App\\Entity\\Course' . "\0" . 'courseClient'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Course $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCourseClient(): ?\App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseClient', []);

        return parent::getCourseClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseClient(\App\Entity\Client $courseClient): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseClient', [$courseClient]);

        return parent::setCourseClient($courseClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseNumtransaction(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCourseNumtransaction();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseNumtransaction', []);

        return parent::getCourseNumtransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseNbpassagers(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseNbpassagers', []);

        return parent::getCourseNbpassagers();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseNbpassagers(int $courseNbpassagers): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseNbpassagers', [$courseNbpassagers]);

        return parent::setCourseNbpassagers($courseNbpassagers);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseHeuredepart(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseHeuredepart', []);

        return parent::getCourseHeuredepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseHeuredepart(\DateTimeInterface $courseHeuredepart): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseHeuredepart', [$courseHeuredepart]);

        return parent::setCourseHeuredepart($courseHeuredepart);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseHeurearrivee(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseHeurearrivee', []);

        return parent::getCourseHeurearrivee();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseHeurearrivee(\DateTimeInterface $courseHeurearrivee): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseHeurearrivee', [$courseHeurearrivee]);

        return parent::setCourseHeurearrivee($courseHeurearrivee);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseStatut(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseStatut', []);

        return parent::getCourseStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseStatut(string $courseStatut): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseStatut', [$courseStatut]);

        return parent::setCourseStatut($courseStatut);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoursePrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoursePrix', []);

        return parent::getCoursePrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoursePrix(float $coursePrix): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoursePrix', [$coursePrix]);

        return parent::setCoursePrix($coursePrix);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseDistance(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseDistance', []);

        return parent::getCourseDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseDistance(float $courseDistance): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseDistance', [$courseDistance]);

        return parent::setCourseDistance($courseDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehiculeNumplaques(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehiculeNumplaques', []);

        return parent::getVehiculeNumplaques();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehiculeNumplaques(string $vehiculeNumplaques): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehiculeNumplaques', [$vehiculeNumplaques]);

        return parent::setVehiculeNumplaques($vehiculeNumplaques);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAdressearrivee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAdressearrivee', []);

        return parent::getIdAdressearrivee();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAdressearrivee(int $idAdressearrivee): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAdressearrivee', [$idAdressearrivee]);

        return parent::setIdAdressearrivee($idAdressearrivee);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdStatutcourse(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdStatutcourse', []);

        return parent::getIdStatutcourse();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdStatutcourse(int $idStatutcourse): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdStatutcourse', [$idStatutcourse]);

        return parent::setIdStatutcourse($idStatutcourse);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdFacture(): ?\App\Entity\Facture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFacture', []);

        return parent::getIdFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdFacture(?\App\Entity\Facture $idFacture): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdFacture', [$idFacture]);

        return parent::setIdFacture($idFacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAdressedepart(): ?\App\Entity\Adresse
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAdressedepart', []);

        return parent::getIdAdressedepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAdressedepart(?\App\Entity\Adresse $idAdressedepart): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAdressedepart', [$idAdressedepart]);

        return parent::setIdAdressedepart($idAdressedepart);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdClient(): ?\App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdClient', []);

        return parent::getIdClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdClient(?\App\Entity\Client $idClient): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdClient', [$idClient]);

        return parent::setIdClient($idClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmploye(): ?\App\Entity\Employes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmploye', []);

        return parent::getIdEmploye();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmploye(?\App\Entity\Employes $idEmploye): \App\Entity\Course
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmploye', [$idEmploye]);

        return parent::setIdEmploye($idEmploye);
    }

}
