<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSFkl2az\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSFkl2az/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSFkl2az.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSFkl2az\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSFkl2az\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SFkl2az',
    'container.build_id' => '71142e67',
    'container.build_time' => 1554650400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSFkl2az');
