<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHHlUdsX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHHlUdsX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHHlUdsX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHHlUdsX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHHlUdsX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HHlUdsX',
    'container.build_id' => 'ee75da1e',
    'container.build_time' => 1553013062,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHHlUdsX');
