<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHYVJRj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHYVJRj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHYVJRj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHYVJRj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXHYVJRj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XHYVJRj',
    'container.build_id' => '20abdcb0',
    'container.build_time' => 1553173432,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHYVJRj');
